---
apiVersion: v1
kind: Secret
metadata:
  # Jenkins ID
  name: "azure-vault-client-id"
  labels:
      # Credential Type
    "jenkins.io/credentials-type": "secretText"
  annotations:
      # Credential Descriptionn
      # Remark: It can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "Azure Service Principale client id to retrieve gpg key"
type: Opaque
data:
  # UTF-8 base64 encoded
  text: {{ .Values.azure_vault_client_id | b64enc }}
