---
apiVersion: v1
kind: Secret
metadata:
  # Jenkins ID
  name: "maven-repository-username"
  labels:
      # Credential Type
    "jenkins.io/credentials-type": "secretText"
  annotations:
      # Credential Descriptionn
      # Remark: It can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "Username used by maven release plugin to publish artifacts on a maven repository"
type: Opaque
data:
  # UTF-8 base64 encoded
  text: {{ .Values.maven_repository_username | b64enc }}
