---
apiVersion: v1
kind: Secret
metadata:
  # Jenkins ID
  name: "signing-cert-pass"
  labels:
      # Credential Type
    "jenkins.io/credentials-type": "secretText"
  annotations:
      # Credential Descriptionn
      # Remark: It can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "Password used by maven signer plugin to unlock the signing certificate"
type: Opaque
data:
  # UTF-8 base64 encoded
  text: {{ .Values.release_certificate_password | b64enc }}
