apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "release-key"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "SSH private key to commit on jenkinsci/jenkins "
type: Opaque
data:
# base64 encoded username
  username: {{ .Values.ssh_release_username | b64enc }}
  privateKey: {{ .Values.ssh_release_privkey | b64enc }}
